### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alexus37** [ProGamerGov/pytorch-old-tensorflow-models#2]
Hey,
first I want to thank you for creating the Repo, it was very helpful so far for me. 
Now I started looking into the exact output of the torch model and compared it with the TensorFlow model, however, they don't seem to match. 
Could you please explain how you converted the TensorFlow model to Pytorch and that the proper input should be?

This is how I use it on the torch side
```python
    model = Inception5h()
    fileurl = "https://github.com/ProGamerGov/pytorch-old-tensorflow-models/raw/master/inception5h.pth"
    model.load_state_dict(load_state_dict_from_url(fileurl))

    np.random.seed(0)
    input_image = np.float32(np.random.randn(224, 224, 3))
    torch_input = transforms.ToTensor()(input_image).unsqueeze_(0)
    output = model(torch_input)
    output_np = output.detach().numpy()
    np.save("torch_output.npy", output_np)
```

and on the tensorflow side:
```python
      graph = tf.Graph()
    sess = tf.InteractiveSession(graph=graph)

    t_input = tf.placeholder(np.float32, name="our_input")  # define the input tensor
    t_preprocessed = tf.expand_dims(t_input, 0)

    with gfile.FastGFile("./tensorflow_inception_graph.pb", "rb") as f:
        graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    tf.import_graph_def(graph_def, {"input": t_preprocessed})

    def T(layer_name):
        return graph.get_tensor_by_name("import/%s:0" % layer_name)

    np.random.seed(0)
    input_image = np.float32(np.random.randn(224, 224, 3))
    softmax = T("softmax2")
    output = sess.run(softmax, {t_input: input_image})
    np.save("tf_output.npy", output)
```

If I compare the resulting output it is not identical, is this expected or am I missing something?

Thanks for your feedback!

![Selection_064](https://user-images.githubusercontent.com/7422767/112021532-ae5e3500-8b31-11eb-9bed-564126e0100d.png)

**Comment by ProGamerGov** [comment]
@alexus37 Thank you for looking into the results of the model! I used [MMdnn](https://github.com/microsoft/MMdnn), but it made a few assumptions that turned out to be incorrect (like the local response norm values, and it did the conv2d same layers differently). This version of the model class should work exactly like the TensorFlow model: https://github.com/ProGamerGov/captum/blob/optim-wip-activation-atlas/captum/optim/_models/inception_v1.py

If you're able to figure out the exact issue with the model in this repository, please submit a PR! The issue is with the class code, and not the model file / weights.

**Comment by alexus37** [comment]
Thanks for the feedback! I will take a look, otherwise could you please provide the weights `inception_v1.py` so I can compare it to the TensorFlow version? 

The file referenced in the code contains the wrong layer names.
```python
GS_SAVED_WEIGHTS_URL = (
    "https://github.com/pytorch/captum/raw/"
    + "optim-wip/captum/optim/_models/inception5h.pth"
)
```

```
Missing key(s) in state_dict: "conv1.weight", "conv1.bias", "conv2.weight", "conv2.bias", "conv3.weight", "conv3.bias", "mixed3a.conv_1x1.weight", "mixed3a.conv_1x1.bias", "mixed3a.conv_3x3_reduce.weight", "mixed3a.conv_3x3_reduce.bias", "mixed3a.conv_3x3.weight", "mixed3a.conv_3x3.bias", "mixed3a.conv_5x5_reduce.weight", "mixed3a.conv_5x5_reduce.bias"...
```

**Comment by ProGamerGov** [comment]
@alexus37 You're getting that error because I altered the layer names in the code I linked to so that they'd be more human readable. I would recommend using the layer class from the file I linked to as it's been setup to accept the new names, if you want to use the `GS_SAVED_WEIGHTS_URL` version of the model.

The `GS_SAVED_WEIGHTS_URL` model file is also the exact same as the model file in this repository (in fact it came from this repository), with the only difference being the layer names.
